/**
 * Open a pull request for the patches Ranger produced, with embedded before/
 * after/target screenshots so the diff is legible at a glance.
 *
 * GitHub PR bodies render images by URL, so we commit the screenshots to a
 * tracked folder on the branch and reference them. For PRIVATE repos we must use
 * the same-origin `github.com/<owner>/<repo>/raw/<branch>/<path>` form: GitHub
 * does not camo-proxy private content, so the viewer's browser fetches the image
 * with its github.com session cookies. The cross-origin raw.githubusercontent.com
 * form has no session auth and renders broken on private repos. Requires `gh`
 * installed + authenticated; otherwise the branch is pushed and the body saved
 * to disk for manual PR creation.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { repoRoot } from "../config.ts";
import type { Discrepancy } from "./detect.ts";

export interface PrScreen {
  name: string;
  before: Buffer | null;
  after: Buffer | null;
  target: Buffer | null;
}

function git(args: string[]): string {
  return execFileSync("git", args, { cwd: repoRoot, encoding: "utf8" }).trim();
}

function remoteSlug(): { owner: string; repo: string } | null {
  try {
    const m = git(["remote", "get-url", "origin"]).match(/github\.com[:/]([^/]+)\/(.+?)(?:\.git)?$/);
    if (m) return { owner: m[1], repo: m[2] };
  } catch {
    /* no origin */
  }
  return null;
}

export async function openPullRequest(opts: {
  branch: string;
  runId: string;
  screens: PrScreen[];
  discrepancies: Discrepancy[];
  success: boolean;
}): Promise<void> {
  const { branch, runId, screens, discrepancies, success } = opts;

  // Ranger commits each kept patch as a checkpoint during the loop, so by now
  // the patch is in history (working tree may be clean). Bail only if the branch
  // has no commits beyond its upstream base — i.e. nothing worth a PR.
  let aheadOfBase = true;
  try {
    const base = git(["merge-base", "HEAD", "origin/main"]);
    aheadOfBase = git(["rev-list", "--count", `${base}..HEAD`]) !== "0";
  } catch {
    /* no origin/main to compare against; assume there's something to PR */
  }
  if (!aheadOfBase) {
    console.log("\nNo kept patches on the branch — skipping PR.");
    return;
  }

  // 1. Write screenshot assets to a tracked dir so they render in the body.
  const relDir = join("tooling", "parity", "pr-assets", runId);
  const absDir = join(repoRoot, relDir);
  mkdirSync(absDir, { recursive: true });
  for (const s of screens) {
    if (s.target) writeFileSync(join(absDir, `${s.name}.target.png`), s.target);
    if (s.before) writeFileSync(join(absDir, `${s.name}.before.png`), s.before);
    if (s.after) writeFileSync(join(absDir, `${s.name}.after.png`), s.after);
  }

  // 2. Commit patch + assets, push the branch.
  git(["add", "-A"]);
  git(["commit", "-m", `Ranger: parity patches + visual evidence (${runId})`]);
  git(["push", "-u", "origin", branch]);

  // 3. Build the PR body with embedded raw images (branch is now pushed).
  const slug = remoteSlug();
  const relUrl = relDir.split("\\").join("/");
  // Same-origin github.com/raw form so images render in PRIVATE repos (the
  // viewer's session authenticates the fetch; raw.githubusercontent would not).
  const raw = (file: string) =>
    slug
      ? `https://github.com/${slug.owner}/${slug.repo}/raw/${branch}/${relUrl}/${file}`
      : `${relUrl}/${file}`;

  const screenBlocks = screens
    .map((s) => {
      const imgs: string[] = [];
      if (s.target) imgs.push(`real Jira (target)\n\n![${s.name} target](${raw(`${s.name}.target.png`)})`);
      if (s.before) imgs.push(`before\n\n![${s.name} before](${raw(`${s.name}.before.png`)})`);
      if (s.after) imgs.push(`after\n\n![${s.name} after](${raw(`${s.name}.after.png`)})`);
      return `### ${s.name}\n\n${imgs.join("\n\n")}`;
    })
    .join("\n\n");

  const discList = discrepancies.length
    ? discrepancies.map((d) => `- **[${d.screen} · ${d.axis} · ${d.severity}]** ${d.summary}`).join("\n")
    : "_none reported_";

  const body = `## Ranger parity patch

The autonomous parity loop (\`tooling/parity\`) compared Jirassic Park against real Jira, patched the gaps, and verified the result.

**Outcome:** ${success ? "parity reached ✅" : "stopped before full parity — review needed ⚠️"}

### Discrepancies addressed
${discList}

## Visual evidence
${screenBlocks}

---
_Generated by Ranger (run \`${runId}\`). Patches were produced by a Cursor coding agent, gated by a deterministic focus-region pixel guardrail plus an Opus judge._`;

  const bodyFile = join(tmpdir(), `ranger-pr-${runId}.md`);
  writeFileSync(bodyFile, body);

  // 4. Create the PR.
  try {
    const url = execFileSync(
      "gh",
      ["pr", "create", "--title", `Ranger: parity patches (${runId})`, "--body-file", bodyFile, "--head", branch],
      { cwd: repoRoot, encoding: "utf8" },
    ).trim();
    console.log(`\nOpened PR: ${url}`);
  } catch (e) {
    console.error(`\nCould not run \`gh pr create\` (${(e as Error).message.split("\n")[0]}).`);
    console.error(`Branch '${branch}' was pushed. Create the PR manually; body saved at ${bodyFile}.`);
  }
}
