"""DEBT (Tech Debt) issues - ~50 issues."""

from __future__ import annotations


ISSUES = [
    # ---- Sprint 1 active ----
    {
        "id_hint": 1,
        "type": "Story",
        "summary": "Refactor `OrderService` - extract pricing logic",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_tomas_silva",
        "story_points": 5,
        "labels": ["tech-debt", "backend"],
        "sprint": "sprint_debt_1",
        "description": (
            "`OrderService` is a god-object. Extract pricing calculation into "
            "`PricingService` and add a contract test. No behavior change."
        ),
        "created_offset_days": -10,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 2,
        "type": "Story",
        "summary": "Delete dead code path: `legacy_v1_payment.go`",
        "status": "Done",
        "priority": "Low",
        "owner": "user_emma_rossi",
        "story_points": 2,
        "labels": ["tech-debt", "backend"],
        "sprint": "sprint_debt_1",
        "created_offset_days": -7,
        "updated_offset_days": -3,
        "resolution": "Fixed",
    },
    {
        "id_hint": 3,
        "type": "Task",
        "summary": "Migrate remaining `print()` to structured logger in `etl/`",
        "status": "In Progress",
        "priority": "Low",
        "owner": "user_owen_walsh",
        "story_points": 3,
        "labels": ["tech-debt", "backend", "blocked"],
        "sprint": "sprint_debt_1",
        "created_offset_days": -8,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 4,
        "type": "Story",
        "summary": "Consolidate three nearly-identical retry helpers",
        "status": "In Review",
        "priority": "Low",
        "owner": "user_maya_chen",
        "story_points": 3,
        "labels": ["tech-debt", "backend"],
        "sprint": "sprint_debt_1",
        "created_offset_days": -9,
        "updated_offset_days": -2,
    },
    {
        "id_hint": 5,
        "type": "Task",
        "summary": "Remove the unused `feature_flag_v0` table",
        "status": "To Do",
        "priority": "Lowest",
        "owner": "user_owen_walsh",
        "story_points": 1,
        "labels": ["tech-debt", "database"],
        "sprint": "sprint_debt_1",
        "created_offset_days": -7,
        "updated_offset_days": -3,
    },
]

FILLER = [
    ("Bug", "Date parsing assumes UTC offset of +00:00", "Backlog", "Medium", ["tech-debt", "backend"]),
    ("Task", "Drop Python 2 compatibility shims", "Backlog", "Low", ["tech-debt"]),
    ("Story", "Replace ad-hoc retry loops with `tenacity`", "Backlog", "Low", ["tech-debt", "backend"]),
    ("Task", "Delete commented-out code in `payments/`", "Backlog", "Lowest", ["tech-debt"]),
    ("Bug", "Off-by-one in pagination of `/users`", "Backlog", "Medium", ["api"]),
    ("Task", "Inline old `Helper` utility methods", "Backlog", "Lowest", ["tech-debt", "backend"]),
    ("Story", "Convert PHP cron jobs to scheduled lambdas", "Backlog", "Medium", ["tech-debt", "infra", "migration"]),
    ("Task", "Type-hint `app/orders.py`", "Backlog", "Low", ["tech-debt", "backend"]),
    ("Bug", "Test runner emits ResourceWarning on every run", "Backlog", "Low", ["tech-debt", "testing"]),
    ("Task", "Move `requirements.txt` to pyproject.toml", "Backlog", "Low", ["tech-debt"]),
    ("Story", "Replace bespoke CSV parser with stdlib", "Backlog", "Low", ["tech-debt", "backend"]),
    ("Task", "Delete `TODO` comments older than 6 months", "Backlog", "Lowest", ["tech-debt", "documentation"]),
    ("Bug", "Pagination breaks at exactly 100 items", "Backlog", "Medium", ["api"]),
    ("Story", "Drop direct sqlalchemy 1.4 patterns", "Backlog", "Low", ["tech-debt", "backend"]),
    ("Task", "Sunset the legacy admin panel", "Backlog", "Medium", ["tech-debt"]),
    ("Bug", "Race condition in invoice number assignment", "Backlog", "High", ["backend", "regression"]),
    ("Task", "Convert remaining `unittest` tests to pytest", "Backlog", "Low", ["tech-debt", "testing"]),
    ("Story", "Eliminate `from foo import *` patterns", "Backlog", "Lowest", ["tech-debt"]),
    ("Task", "Document the order state machine", "Backlog", "Low", ["documentation"]),
    ("Bug", "Soft-deleted users appear in mention search", "Backlog", "Medium", ["api"]),
    ("Story", "Consolidate currency formatting helpers", "Backlog", "Low", ["tech-debt"]),
    ("Task", "Drop support for IE11 in admin UI", "Backlog", "Low", ["tech-debt"]),
    ("Story", "Move `migrations/` to alembic", "Backlog", "Medium", ["tech-debt", "migration", "database"]),
    ("Bug", "Caching layer evicts on benign 4xx", "Backlog", "Medium", ["backend", "performance"]),
    ("Task", "Delete unused Stripe webhook handlers", "Backlog", "Low", ["tech-debt"]),
    ("Story", "Add deprecation warnings to v1 API endpoints", "Backlog", "Medium", ["api", "tech-debt"]),
    ("Task", "Migrate Slack notifications off legacy bot", "Backlog", "Low", ["tech-debt", "migration"]),
    ("Bug", "Email templates render plain-text only on Outlook", "Backlog", "Low", ["backend"]),
    ("Story", "Reduce `OrderRepository` complexity", "Backlog", "Medium", ["tech-debt", "backend"]),
    ("Task", "Consolidate three different `Money` types", "Backlog", "Medium", ["tech-debt", "backend"]),
    ("Bug", "Currency conversion not idempotent", "Backlog", "Medium", ["backend"]),
    ("Task", "Replace bespoke parser with `pyparsing` in admin", "Backlog", "Low", ["tech-debt"]),
    ("Story", "Drop hand-rolled DI container", "Backlog", "Medium", ["tech-debt", "backend"]),
    ("Task", "Remove dead AppEngine entry points", "Backlog", "Low", ["tech-debt"]),
    ("Bug", "Stale denormalized counters in user feed", "Backlog", "Medium", ["backend", "database"]),
    ("Story", "Move documentation site from Sphinx to mkdocs", "Backlog", "Low", ["documentation", "tech-debt"]),
    ("Task", "Delete `experiments/` folder", "Backlog", "Lowest", ["tech-debt"]),
    ("Bug", "Trailing whitespace in CSV exports", "Backlog", "Lowest", ["backend"]),
    ("Story", "Drop synchronous email sending", "Backlog", "Medium", ["backend", "performance"]),
    ("Task", "Delete `_old.py` files across the repo", "Backlog", "Lowest", ["tech-debt"]),
    ("Bug", "Search index includes deleted records", "Backlog", "High", ["backend"]),
    ("Story", "Standardize on `httpx` instead of `requests`", "Backlog", "Low", ["tech-debt", "backend"]),
    ("Task", "Remove the legacy mobile webhook endpoint", "Backlog", "Low", ["tech-debt", "api"]),
    ("Story", "Re-key the cache from string-IDs to ints", "Backlog", "Medium", ["backend", "performance"]),
    ("Task", "Add type stubs for the `boto3` overrides", "Backlog", "Low", ["tech-debt", "backend"]),
]
