"""PLAT (Platform Engineering) issues - ~70 issues."""

from __future__ import annotations


ISSUES = [
    # ---- Epic + closed sprint 8 ----
    {
        "id_hint": 1,
        "type": "Epic",
        "summary": "Blue/green deployment pipeline",
        "status": "In Progress",
        "priority": "High",
        "owner": "user_raj_patel",
        "story_points": 21,
        "labels": ["infra", "q3-okr"],
        "sprint": "sprint_plat_9",
        "description": (
            "Replace the legacy single-environment deploy with a true blue/green pipeline that "
            "supports zero-downtime swaps, fast rollback, and progressive traffic shifting."
        ),
        "created_offset_days": -90,
        "updated_offset_days": -1,
        "watchers": ["user_admin", "user_sarah_kim", "user_maya_chen"],
    },
    {
        "id_hint": 2,
        "type": "Story",
        "summary": "Provision green environment in staging",
        "status": "Done",
        "priority": "High",
        "owner": "user_marcus_obrien",
        "story_points": 5,
        "labels": ["infra"],
        "sprint": "sprint_plat_8",
        "epic": 1,
        "created_offset_days": -45,
        "updated_offset_days": -30,
        "resolution": "Fixed",
    },
    {
        "id_hint": 3,
        "type": "Story",
        "summary": "Build deploy CLI for blue/green swap",
        "status": "In Progress",
        "priority": "High",
        "owner": "user_lina_garcia",
        "story_points": 8,
        "labels": ["infra", "blocked"],
        "sprint": "sprint_plat_9",
        "epic": 1,
        "created_offset_days": -28,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 4,
        "type": "Story",
        "summary": "Wire traffic-shifting via the load balancer",
        "status": "In Review",
        "priority": "High",
        "owner": "user_aki_yamada",
        "story_points": 5,
        "labels": ["infra"],
        "sprint": "sprint_plat_9",
        "epic": 1,
        "created_offset_days": -21,
        "updated_offset_days": -2,
    },
    {
        "id_hint": 5,
        "type": "Story",
        "summary": "Runbook + dry run on staging",
        "status": "To Do",
        "priority": "High",
        "owner": "user_raj_patel",
        "story_points": 3,
        "labels": ["infra", "documentation"],
        "sprint": "sprint_plat_9",
        "epic": 1,
        "created_offset_days": -14,
        "updated_offset_days": -7,
    },

    # ---- Active sprint 9 - non-epic ----
    {
        "id_hint": 6,
        "type": "Bug",
        "summary": "API rate limiter does not respect X-Forwarded-For",
        "status": "In Progress",
        "priority": "Highest",
        "owner": "user_noah_williams",
        "story_points": 3,
        "labels": ["api", "security", "regression"],
        "sprint": "sprint_plat_9",
        "description": (
            "Rate limiter is keying on the connection IP instead of the originating "
            "client IP from `X-Forwarded-For`. Behind our CDN this means we're "
            "rate-limiting CDN edges, not users.\n\n"
            "Caught after a customer reported sporadic 429s during peak. Filing as "
            "Highest because in the worst case we're effectively DoSing ourselves."
        ),
        "created_offset_days": -3,
        "updated_offset_days": 0,
        "watchers": ["user_admin", "user_devon_lee"],
        "custom_fields": {"cf_severity": "S1 - Critical"},
    },
    {
        "id_hint": 7,
        "type": "Task",
        "summary": "Backfill metrics for the auth service",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_grace_okafor",
        "story_points": 3,
        "labels": ["infra"],
        "sprint": "sprint_plat_9",
        "created_offset_days": -10,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 8,
        "type": "Task",
        "summary": "Retire the legacy deploy script `legacy_push.sh`",
        "status": "To Do",
        "priority": "Low",
        "owner": "user_marcus_obrien",
        "story_points": 2,
        "labels": ["infra", "tech-debt"],
        "sprint": "sprint_plat_9",
        "created_offset_days": -5,
        "updated_offset_days": -5,
    },
    {
        "id_hint": 9,
        "type": "Story",
        "summary": "Standardize on slog for Go services",
        "status": "In Review",
        "priority": "Medium",
        "owner": "user_raj_patel",
        "story_points": 5,
        "labels": ["backend", "tech-debt"],
        "sprint": "sprint_plat_9",
        "created_offset_days": -14,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 10,
        "type": "Bug",
        "summary": "Cloudwatch alarms fire on stale data after lambda cold start",
        "status": "To Do",
        "priority": "Medium",
        "owner": "user_lina_garcia",
        "story_points": 3,
        "labels": ["infra", "regression"],
        "sprint": "sprint_plat_9",
        "created_offset_days": -8,
        "updated_offset_days": -2,
    },
    {
        "id_hint": 11,
        "type": "Task",
        "summary": "Add SLO dashboard for the search service",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_grace_okafor",
        "story_points": 3,
        "labels": ["infra"],
        "sprint": "sprint_plat_9",
        "created_offset_days": -6,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 12,
        "type": "Bug",
        "summary": "Search service tokenizer rejects non-ASCII",
        "status": "In Progress",
        "priority": "Highest",
        "owner": "user_noah_williams",
        "story_points": 3,
        "labels": ["urgent", "regression", "backend"],
        "sprint": "sprint_plat_9",
        "description": (
            "Root cause for SCRUM-10. The tokenizer rejects non-ASCII silently and "
            "the search service falls through to a 500. Fix: enable unicode-aware "
            "tokenizing and add a graceful 400 for queries we genuinely cannot index."
        ),
        "created_offset_days": -2,
        "updated_offset_days": 0,
        "watchers": ["user_sarah_kim", "user_admin"],
    },

    # ---- Closed sprint 8 leftovers ----
    {
        "id_hint": 13,
        "type": "Story",
        "summary": "OpenTelemetry traces for the API gateway",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_lina_garcia",
        "story_points": 5,
        "labels": ["infra"],
        "sprint": "sprint_plat_8",
        "created_offset_days": -40,
        "updated_offset_days": -30,
        "resolution": "Fixed",
    },
    {
        "id_hint": 14,
        "type": "Story",
        "summary": "Loki log retention bumped to 30 days",
        "status": "Done",
        "priority": "Low",
        "owner": "user_aki_yamada",
        "story_points": 2,
        "labels": ["infra"],
        "sprint": "sprint_plat_8",
        "created_offset_days": -38,
        "updated_offset_days": -32,
        "resolution": "Fixed",
    },
    {
        "id_hint": 15,
        "type": "Task",
        "summary": "Document on-call rotations in handbook",
        "status": "Done",
        "priority": "Low",
        "owner": "user_raj_patel",
        "story_points": 1,
        "labels": ["documentation"],
        "sprint": "sprint_plat_8",
        "created_offset_days": -35,
        "updated_offset_days": -33,
        "resolution": "Fixed",
    },
    {
        "id_hint": 16,
        "type": "Bug",
        "summary": "Grafana dashboard for queue depth shows wrong units",
        "status": "Done",
        "priority": "Low",
        "owner": "user_marcus_obrien",
        "story_points": 1,
        "labels": ["infra"],
        "sprint": "sprint_plat_8",
        "created_offset_days": -36,
        "updated_offset_days": -30,
        "resolution": "Fixed",
    },

    # ---- Future sprint ----
    {
        "id_hint": 17,
        "type": "Story",
        "summary": "Right-size t3 instances based on past 30d usage",
        "status": "Backlog",
        "priority": "Medium",
        "owner": "user_aki_yamada",
        "story_points": 5,
        "labels": ["infra", "performance"],
        "sprint": "sprint_plat_10",
        "created_offset_days": -15,
        "updated_offset_days": -5,
    },
    {
        "id_hint": 18,
        "type": "Story",
        "summary": "Consolidate RDS instances - dev/staging",
        "status": "Backlog",
        "priority": "Medium",
        "owner": "user_lina_garcia",
        "story_points": 5,
        "labels": ["infra", "database"],
        "sprint": "sprint_plat_10",
        "created_offset_days": -14,
        "updated_offset_days": -5,
    },
    {
        "id_hint": 19,
        "type": "Task",
        "summary": "Migrate from elasticache redis 6 to 7",
        "status": "Backlog",
        "priority": "Medium",
        "owner": "user_noah_williams",
        "story_points": 5,
        "labels": ["infra", "migration"],
        "sprint": "sprint_plat_10",
        "created_offset_days": -12,
        "updated_offset_days": -5,
    },

    # ---- Stale unassigned backlog ----
    {
        "id_hint": 20,
        "type": "Bug",
        "summary": "Lambda concurrency reservation drifts from terraform state",
        "status": "Backlog",
        "priority": "Medium",
        "owner": None,
        "labels": ["infra"],
        "created_offset_days": -120,
        "updated_offset_days": -88,
    },
    {
        "id_hint": 21,
        "type": "Story",
        "summary": "Self-service feature flag UI for non-engineers",
        "status": "Backlog",
        "priority": "Low",
        "owner": None,
        "story_points": 8,
        "labels": ["infra"],
        "created_offset_days": -100,
        "updated_offset_days": -70,
    },
    {
        "id_hint": 22,
        "type": "Story",
        "summary": "Centralized secrets via vault",
        "status": "Backlog",
        "priority": "High",
        "owner": None,
        "story_points": 13,
        "labels": ["security", "infra"],
        "created_offset_days": -95,
        "updated_offset_days": -60,
    },
]

FILLER = [
    ("Bug", "S3 lifecycle policy mismatch on logs bucket", "Backlog", "Low", ["infra"]),
    ("Task", "Bump Terraform AWS provider to v5", "Backlog", "Low", ["infra", "tech-debt"]),
    ("Story", "Self-serve database snapshots for engineers", "Backlog", "Medium", ["infra", "database"]),
    ("Bug", "ALB health check too aggressive during deploy", "Backlog", "Medium", ["infra"]),
    ("Task", "Audit IAM roles for least privilege", "Backlog", "Medium", ["security", "infra"]),
    ("Story", "Per-team cost reports", "Backlog", "Medium", ["infra"]),
    ("Bug", "Kafka partitions skewed after broker restart", "Backlog", "Medium", ["infra"]),
    ("Task", "Move CI runners off macOS 12", "Backlog", "Low", ["infra"]),
    ("Story", "Synthetic checks for the auth flow", "Backlog", "Medium", ["infra", "testing"]),
    ("Bug", "DNS TTL too long for ALB swap", "Backlog", "Medium", ["infra"]),
    ("Task", "Document runbook for the search service", "Backlog", "Low", ["documentation", "infra"]),
    ("Story", "GitHub Actions cache for Go builds", "Backlog", "Low", ["infra", "performance"]),
    ("Bug", "Prometheus retention bucket pegged at 100%", "Backlog", "High", ["infra"]),
    ("Task", "Rotate slack incoming-webhook secrets", "Backlog", "Low", ["security"]),
    ("Story", "Improve cold-start time on the auth lambda", "Backlog", "Medium", ["infra", "performance"]),
    ("Bug", "VPC peering route table drift on dev", "Backlog", "Low", ["infra"]),
    ("Task", "Move from AWS CodeBuild to GitHub Actions", "Backlog", "Medium", ["infra", "migration"]),
    ("Story", "Standard linting CI step for all repos", "Backlog", "Low", ["infra", "tech-debt"]),
    ("Bug", "EKS node group rolling update stalls", "Backlog", "Medium", ["infra"]),
    ("Task", "Add Trivy scanning to docker builds", "Backlog", "Medium", ["security", "infra"]),
    ("Story", "Internal docs site search", "Backlog", "Low", ["infra"]),
    ("Bug", "Athena query timeouts under heavy load", "Backlog", "Medium", ["infra", "performance"]),
    ("Task", "Decommission legacy `analytics-old` cluster", "Backlog", "Low", ["infra", "tech-debt"]),
    ("Bug", "Slack alerts have stale playbook links", "Backlog", "Low", ["documentation"]),
    ("Story", "Better runbook automation via incident bot", "Backlog", "Medium", ["infra"]),
    ("Task", "Sunset Python 3.9 base image", "Backlog", "Low", ["infra", "tech-debt"]),
    ("Bug", "Datadog APM tag explosion on hot endpoint", "Backlog", "Medium", ["infra", "performance"]),
    ("Story", "Add network policies to k8s namespaces", "Backlog", "Medium", ["security", "infra"]),
    ("Task", "Backup verification cronjob", "Backlog", "Medium", ["infra", "database"]),
    ("Bug", "Spot instance interruptions not handled by job runner", "Backlog", "Medium", ["infra"]),
    ("Story", "Cost-anomaly alerts via CUR", "Backlog", "Low", ["infra"]),
    ("Task", "Replace deprecated AWS SDK v2 calls", "Backlog", "Low", ["tech-debt"]),
    ("Bug", "Cloudfront cache key includes auth header inadvertently", "Backlog", "High", ["security", "infra"]),
    ("Task", "Standard pre-commit config across repos", "Backlog", "Low", ["tech-debt"]),
    ("Story", "Service catalog with ownership metadata", "Backlog", "Medium", ["infra", "documentation"]),
    ("Bug", "Memory leak in the staging job runner", "Backlog", "Medium", ["infra", "performance"]),
    ("Task", "Migrate from CircleCI to GitHub Actions for backend repos", "Backlog", "Medium", ["infra", "migration"]),
    ("Story", "Tracing-aware HTTP client wrapper", "Backlog", "Medium", ["backend"]),
    ("Bug", "ECS task definition drift after console edits", "Backlog", "Low", ["infra"]),
    ("Task", "Document outage classes and pager severity matrix", "Backlog", "Low", ["documentation"]),
    ("Story", "Add canary deploys for the API gateway", "Backlog", "Medium", ["infra"]),
    ("Task", "Move secrets from env vars to mounted files", "Backlog", "Medium", ["security", "infra"]),
    ("Bug", "Race in service mesh sidecar startup", "Backlog", "High", ["infra"]),
    ("Story", "Test dashboards in CI", "Backlog", "Low", ["infra", "testing"]),
    ("Task", "Refactor terraform modules to v4 layout", "Backlog", "Low", ["infra", "tech-debt"]),
    ("Bug", "WAF rule blocks healthy bot traffic", "Backlog", "Medium", ["infra", "security"]),
    ("Story", "Reusable terraform modules for new services", "Backlog", "Medium", ["infra"]),
]
