"""SCRUM (Mobile App) issues - ~80 issues.

Hand-curated showpiece issues for the active sprint, the cross-team epic, and
a few past sprints. Backlog filler is a smaller curated list (no Faker).

Schema for each entry:
    summary: required
    type: Story | Task | Bug | Epic | Subtask  (default Task)
    status: status name (default Backlog)
    priority: Lowest|Low|Medium|High|Highest (default Medium)
    owner: user id or None for unassigned
    reporter: user id (defaults to project lead at load time)
    story_points: int or None
    labels: list[str]
    sprint: sprint id or None
    description: optional multi-line string
    epic: epic key (SCRUM-1, etc.) or None
    parent: parent issue key (for subtasks)
    comments: list of {author, body} (threading optional via parent index)
    watchers: list of user ids
    links: list of {type, target}
    created_offset_days: int (relative to seed time, default by sprint)
    updated_offset_days: int
    custom_fields: dict of {custom_field_id: value}
"""

from __future__ import annotations


ISSUES = [
    # ---- Epic: Push Notifications v2 (SCRUM-1, the Sprint 23 anchor) ----
    {
        "id_hint": 1,
        "type": "Epic",
        "summary": "Push Notifications v2",
        "status": "In Progress",
        "priority": "High",
        "owner": "user_sarah_kim",
        "story_points": 21,
        "labels": ["q3-okr", "mobile"],
        "sprint": "sprint_scrum_23",
        "description": (
            "Roll out the next generation of push notifications across iOS and Android.\n\n"
            "**Why**: customer feedback consistently mentions noisy notifications and missing "
            "ones for direct mentions. We want a unified preference UI and a delivery rate above 95%.\n\n"
            "**Out of scope**: web push (tracked under PLAT). In-app banner redesign (separate epic, Q4)."
        ),
        "created_offset_days": -75,
        "updated_offset_days": -1,
        "watchers": ["user_admin", "user_raj_patel", "user_devon_lee"],
        "custom_fields": {"cf_target_release": "v4.2"},
    },
    {
        "id_hint": 2,
        "type": "Story",
        "summary": "Define notification preference UI",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 5,
        "labels": ["mobile", "design-needed"],
        "sprint": "sprint_scrum_22",
        "epic": 1,
        "created_offset_days": -50,
        "updated_offset_days": -28,
        "resolution": "Fixed",
    },
    {
        "id_hint": 3,
        "type": "Story",
        "summary": "Implement notification preference UI - iOS",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_priya_iyer",
        "story_points": 5,
        "labels": ["ios", "mobile"],
        "sprint": "sprint_scrum_22",
        "epic": 1,
        "created_offset_days": -50,
        "updated_offset_days": -29,
        "resolution": "Fixed",
    },
    {
        "id_hint": 4,
        "type": "Story",
        "summary": "Implement notification preference UI - Android",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_jordan_smith",
        "story_points": 5,
        "labels": ["android", "mobile"],
        "sprint": "sprint_scrum_22",
        "epic": 1,
        "created_offset_days": -50,
        "updated_offset_days": -28,
        "resolution": "Fixed",
    },
    {
        "id_hint": 5,
        "type": "Story",
        "summary": "Wire backend delivery telemetry",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_raj_patel",
        "story_points": 3,
        "labels": ["backend", "api"],
        "sprint": "sprint_scrum_22",
        "epic": 1,
        "created_offset_days": -45,
        "updated_offset_days": -30,
        "resolution": "Fixed",
    },
    {
        "id_hint": 6,
        "type": "Story",
        "summary": "Roll out v2 to 10% of iOS users behind a flag",
        "status": "In Progress",
        "priority": "High",
        "owner": "user_priya_iyer",
        "story_points": 5,
        "labels": ["ios", "rollout"],
        "sprint": "sprint_scrum_23",
        "epic": 1,
        "created_offset_days": -14,
        "updated_offset_days": -2,
        "comments": [
            {"author": "user_priya_iyer", "body": "Feature flag wired, waiting on backend to ack delivery events before I crank the percentage."},
            {"author": "user_raj_patel", "body": "Backend's good. Telemetry shows ~98% delivery in dogfood. Send it."},
        ],
    },
    {
        "id_hint": 7,
        "type": "Story",
        "summary": "Roll out v2 to 10% of Android users behind a flag",
        "status": "In Review",
        "priority": "High",
        "owner": "user_sarah_kim",
        "story_points": 5,
        "labels": ["android", "rollout"],
        "sprint": "sprint_scrum_23",
        "epic": 1,
        "created_offset_days": -14,
        "updated_offset_days": -1,
        "comments": [
            {"author": "user_jordan_smith", "body": "PR up: #482. Reviewers, please pay attention to the LiveData lifecycle in `NotificationManager`."},
        ],
    },

    # ---- Active sprint (Sprint 23) - the rest, mixed statuses ----
    {
        "id_hint": 8,
        "type": "Bug",
        "summary": "Login button stays disabled after invalid email",
        "status": "In Progress",
        "priority": "High",
        "owner": "user_priya_iyer",
        "story_points": 2,
        "labels": ["ios", "regression"],
        "sprint": "sprint_scrum_23",
        "description": (
            "After entering an invalid email and tapping Sign In, the button remains "
            "disabled even after the email field is corrected.\n\n"
            "Repro:\n"
            "1. Open app cold\n"
            "2. Tap 'Sign in'\n"
            "3. Enter `not-an-email`\n"
            "4. Tap 'Continue'\n"
            "5. Correct the email to a valid one\n"
            "6. Observe: button stays disabled.\n\n"
            "Expected: button re-enables when input becomes valid.\n\n"
            "Bisected to e8a3f12, the new validation hook."
        ),
        "created_offset_days": -8,
        "updated_offset_days": -1,
        "watchers": ["user_sarah_kim", "user_camille_durand"],
        "custom_fields": {"cf_severity": "S2 - Major"},
        "comments": [
            {"author": "user_chloe_miller", "body": "Repros for me on iOS 17.2, iPhone 15 Pro."},
            {"author": "user_priya_iyer", "body": "Got a fix locally. Validation hook was memoizing on first render and never re-running on the email field update. PR incoming."},
        ],
    },
    {
        "id_hint": 9,
        "type": "Task",
        "summary": "Add retry/backoff to crash reporter upload",
        "status": "To Do",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 3,
        "labels": ["mobile", "regression", "blocked"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -6,
        "updated_offset_days": -3,
    },
    {
        "id_hint": 10,
        "type": "Bug",
        "summary": "Fire drill: Search results return 500 for non-ASCII queries",
        "status": "In Progress",
        "priority": "Highest",
        "owner": "user_sarah_kim",
        "story_points": 3,
        "labels": ["urgent", "regression", "customer-reported"],
        "sprint": "sprint_scrum_23",
        "description": (
            "**Fire drill - added to active sprint mid-cycle.**\n\n"
            "Any search containing accented characters or CJK fails with a 500. We're "
            "seeing ~6% of total searches affected based on the past hour of logs.\n\n"
            "Stack trace points at the new tokenizer in `SearchService.tokenize()`. "
            "Likely a missing `unicode_aware=True`.\n\n"
            "Sarah is on this; rolling back the flag while we ship the proper fix."
        ),
        "created_offset_days": -2,
        "updated_offset_days": 0,
        "watchers": ["user_admin", "user_raj_patel", "user_devon_lee"],
        "custom_fields": {"cf_severity": "S1 - Critical"},
        "links": [{"type": "relates", "target_hint": ("PLAT", 12)}],
    },
    {
        "id_hint": 11,
        "type": "Story",
        "summary": "Inline image previews in the inbox",
        "status": "In Review",
        "priority": "Medium",
        "owner": "user_jordan_smith",
        "story_points": 5,
        "labels": ["android", "mobile"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -10,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 12,
        "type": "Bug",
        "summary": "Pull-to-refresh on iPad does not refresh",
        "status": "To Do",
        "priority": "Low",
        "owner": "user_priya_iyer",
        "story_points": 1,
        "labels": ["ios"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -5,
        "updated_offset_days": -3,
    },
    {
        "id_hint": 13,
        "type": "Task",
        "summary": "Investigate notification battery drain reports",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 3,
        "labels": ["android", "performance", "customer-reported"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -6,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 14,
        "type": "Story",
        "summary": "Refactor auth token storage to use Keychain on iOS",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_priya_iyer",
        "story_points": 3,
        "labels": ["ios", "security"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -10,
        "updated_offset_days": -3,
        "resolution": "Fixed",
    },
    {
        "id_hint": 15,
        "type": "Task",
        "summary": "Sprint 23 retro doc",
        "status": "To Do",
        "priority": "Low",
        "owner": "user_sarah_kim",
        "story_points": 1,
        "labels": ["documentation"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -3,
        "updated_offset_days": -3,
    },
    {
        "id_hint": 16,
        "type": "Bug",
        "summary": "Onboarding skip button disappears after orientation change",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_jordan_smith",
        "story_points": 2,
        "labels": ["android", "regression"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -5,
        "updated_offset_days": -1,
    },

    # ---- Sprint 22 (closed) - completed work ----
    {
        "id_hint": 17,
        "type": "Story",
        "summary": "Password reset deep link from email",
        "status": "Done",
        "priority": "High",
        "owner": "user_priya_iyer",
        "story_points": 5,
        "labels": ["ios", "android"],
        "sprint": "sprint_scrum_22",
        "created_offset_days": -45,
        "updated_offset_days": -29,
        "resolution": "Fixed",
    },
    {
        "id_hint": 18,
        "type": "Bug",
        "summary": "OAuth callback URL ignored on Android 13+",
        "status": "Done",
        "priority": "Highest",
        "owner": "user_jordan_smith",
        "story_points": 3,
        "labels": ["android", "regression"],
        "sprint": "sprint_scrum_22",
        "created_offset_days": -42,
        "updated_offset_days": -30,
        "resolution": "Fixed",
    },
    {
        "id_hint": 19,
        "type": "Task",
        "summary": "Add SwiftUI lint rules for SF Symbols version checks",
        "status": "Done",
        "priority": "Low",
        "owner": "user_camille_durand",
        "story_points": 2,
        "labels": ["ios", "testing"],
        "sprint": "sprint_scrum_22",
        "created_offset_days": -40,
        "updated_offset_days": -30,
        "resolution": "Fixed",
    },
    {
        "id_hint": 20,
        "type": "Bug",
        "summary": "Biometric prompt overlaps modal sheet on iOS 17",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_priya_iyer",
        "story_points": 2,
        "labels": ["ios", "regression"],
        "sprint": "sprint_scrum_22",
        "created_offset_days": -40,
        "updated_offset_days": -30,
        "resolution": "Fixed",
    },
    {
        "id_hint": 21,
        "type": "Story",
        "summary": "Magic-link login fallback",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_jordan_smith",
        "story_points": 5,
        "labels": ["mobile"],
        "sprint": "sprint_scrum_22",
        "created_offset_days": -42,
        "updated_offset_days": -28,
        "resolution": "Fixed",
    },

    # ---- Sprint 21 (closed) - small completed slice ----
    {
        "id_hint": 22,
        "type": "Story",
        "summary": "First-run tutorial screens",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 5,
        "labels": ["mobile"],
        "sprint": "sprint_scrum_21",
        "created_offset_days": -65,
        "updated_offset_days": -44,
        "resolution": "Fixed",
    },
    {
        "id_hint": 23,
        "type": "Bug",
        "summary": "Avatar uploads truncated at 1MB",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_jordan_smith",
        "story_points": 3,
        "labels": ["android", "backend"],
        "sprint": "sprint_scrum_21",
        "created_offset_days": -55,
        "updated_offset_days": -45,
        "resolution": "Fixed",
    },

    # ---- Future sprints ----
    {
        "id_hint": 24,
        "type": "Epic",
        "summary": "Search rewrite",
        "status": "Backlog",
        "priority": "High",
        "owner": "user_sarah_kim",
        "story_points": 34,
        "labels": ["q4-okr", "mobile"],
        "description": "Rebuild search around our new ranking service. Two-sprint epic.",
        "created_offset_days": -25,
        "updated_offset_days": -10,
    },
    {
        "id_hint": 25,
        "type": "Story",
        "summary": "Index docs in the new search service",
        "status": "Backlog",
        "priority": "Medium",
        "owner": "user_priya_iyer",
        "story_points": 8,
        "labels": ["backend"],
        "sprint": "sprint_scrum_24",
        "epic": 24,
        "created_offset_days": -20,
        "updated_offset_days": -10,
    },
    {
        "id_hint": 26,
        "type": "Story",
        "summary": "Mobile UI for new search ranking signals",
        "status": "Backlog",
        "priority": "Medium",
        "owner": "user_jordan_smith",
        "story_points": 5,
        "labels": ["android", "ios"],
        "sprint": "sprint_scrum_24",
        "epic": 24,
        "created_offset_days": -20,
        "updated_offset_days": -10,
    },
    {
        "id_hint": 27,
        "type": "Story",
        "summary": "Saved search filters",
        "status": "Backlog",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 5,
        "labels": ["mobile"],
        "sprint": "sprint_scrum_25",
        "epic": 24,
        "created_offset_days": -15,
        "updated_offset_days": -10,
    },
    {
        "id_hint": 28,
        "type": "Story",
        "summary": "Highlight matched terms in result list",
        "status": "Backlog",
        "priority": "Low",
        "owner": "user_priya_iyer",
        "story_points": 3,
        "labels": ["mobile"],
        "sprint": "sprint_scrum_25",
        "epic": 24,
        "created_offset_days": -12,
        "updated_offset_days": -10,
    },

    # ---- A reopened issue with visible history ----
    {
        "id_hint": 29,
        "type": "Bug",
        "summary": "Profile photo doesn't update after upload until cold restart",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_priya_iyer",
        "story_points": 3,
        "labels": ["ios", "regression"],
        "description": (
            "Originally closed in Sprint 21 but reopened by Devon two weeks ago - the "
            "fix only addressed iOS, the reporter was using Android."
        ),
        "created_offset_days": -60,
        "updated_offset_days": -3,
        "reopened": True,
        "comments": [
            {"author": "user_chloe_miller", "body": "Filed originally - cache invalidation issue."},
            {"author": "user_priya_iyer", "body": "Fixed in #312, marking done."},
            {"author": "user_devon_lee", "body": "This is happening again, my customer was on Android."},
            {"author": "user_priya_iyer", "body": "Reopening - I'll take it again. We need to invalidate the SDImageCache on Android side too."},
        ],
    },

    # ---- Stale backlog issues ----
    {
        "id_hint": 30,
        "type": "Bug",
        "summary": "Dark mode contrast on disabled buttons",
        "status": "Backlog",
        "priority": "Low",
        "owner": None,
        "labels": ["accessibility", "mobile"],
        "created_offset_days": -110,
        "updated_offset_days": -90,
    },
    {
        "id_hint": 31,
        "type": "Story",
        "summary": "Localize error messages into Japanese",
        "status": "Backlog",
        "priority": "Medium",
        "owner": None,
        "story_points": 8,
        "labels": ["mobile"],
        "created_offset_days": -120,
        "updated_offset_days": -85,
    },
    {
        "id_hint": 32,
        "type": "Bug",
        "summary": "Crash when opening app while in airplane mode with pending uploads",
        "status": "Backlog",
        "priority": "Medium",
        "owner": None,
        "story_points": 3,
        "labels": ["regression", "android"],
        "created_offset_days": -75,
        "updated_offset_days": -50,
    },

    # ---- Subtasks under a story ----
    {
        "id_hint": 33,
        "type": "Story",
        "summary": "Refactor onboarding screen for new design system",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 8,
        "labels": ["mobile"],
        "sprint": "sprint_scrum_23",
        "created_offset_days": -20,
        "updated_offset_days": -2,
    },
    {
        "id_hint": 34,
        "type": "Subtask",
        "summary": "Onboarding refactor - typography",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 2,
        "parent": 33,
        "created_offset_days": -18,
        "updated_offset_days": -10,
        "resolution": "Fixed",
    },
    {
        "id_hint": 35,
        "type": "Subtask",
        "summary": "Onboarding refactor - layout",
        "status": "Done",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 3,
        "parent": 33,
        "created_offset_days": -18,
        "updated_offset_days": -8,
        "resolution": "Fixed",
    },
    {
        "id_hint": 36,
        "type": "Subtask",
        "summary": "Onboarding refactor - animations",
        "status": "In Progress",
        "priority": "Medium",
        "owner": "user_camille_durand",
        "story_points": 3,
        "parent": 33,
        "created_offset_days": -15,
        "updated_offset_days": -2,
    },
]

# Filler backlog/done issues to round out to ~80. Hand-curated short titles, no Faker.
FILLER = [
    ("Bug", "Tap target on settings row too small on Android", "Backlog", "Low", ["android", "accessibility"]),
    ("Task", "Update Privacy Policy URL in app footer", "Backlog", "Low", ["mobile", "documentation"]),
    ("Story", "Allow signing in with Apple", "Backlog", "Medium", ["ios"]),
    ("Bug", "Loading spinner persists after timeout on profile screen", "Backlog", "Low", ["mobile"]),
    ("Task", "Bump Kotlin to 2.0", "Backlog", "Low", ["android", "tech-debt"]),
    ("Story", "Add tablet layout for browse view", "Backlog", "Medium", ["android"]),
    ("Bug", "VoiceOver order incorrect on Edit Profile", "Backlog", "Medium", ["accessibility", "ios"]),
    ("Task", "Generate App Store screenshots for v4.2", "Backlog", "Low", ["mobile"]),
    ("Bug", "Long usernames overflow nav bar", "Backlog", "Low", ["mobile"]),
    ("Story", "In-app feedback shortcut (shake to report)", "Backlog", "Low", ["mobile"]),
    ("Bug", "Empty state image cropped on small Androids", "Backlog", "Low", ["android"]),
    ("Task", "Bump iOS deployment target to 16", "Backlog", "Medium", ["ios", "tech-debt"]),
    ("Story", "Show 'New' badge for recently added items", "Backlog", "Low", ["mobile"]),
    ("Bug", "Tabbar icon misaligned on iPad mini portrait", "Backlog", "Low", ["ios"]),
    ("Task", "Replace deprecated `WKWebView` usage", "Backlog", "Low", ["ios", "tech-debt"]),
    ("Story", "Universal links for shared posts", "Backlog", "Medium", ["mobile"]),
    ("Bug", "Crash on Galaxy Fold open transition", "Backlog", "High", ["android", "regression"]),
    ("Bug", "Avatar persists after sign-out", "Backlog", "Medium", ["mobile", "security"]),
    ("Story", "Dark-mode app icon variant", "Backlog", "Lowest", ["mobile"]),
    ("Task", "Add UI snapshot tests for the inbox", "Backlog", "Low", ["mobile", "testing"]),
    ("Bug", "Notification deep link to comment opens wrong post", "Backlog", "Medium", ["mobile"]),
    ("Story", "Offline draft compose mode", "Backlog", "Medium", ["mobile"]),
    ("Bug", "Push token not refreshed after re-install on same device", "Backlog", "Medium", ["mobile"]),
    ("Task", "Migrate Android storage to scoped storage", "Backlog", "Medium", ["android", "tech-debt"]),
    ("Story", "Profile QR code for fast follow", "Backlog", "Low", ["mobile"]),
    ("Bug", "Tutorial replay button does nothing", "Backlog", "Low", ["mobile"]),
    ("Story", "Add Spanish locale", "Backlog", "Medium", ["mobile"]),
    ("Bug", "Image zoom gesture conflicts with horizontal swipe", "Backlog", "Medium", ["ios"]),
    ("Task", "Reduce app bundle size below 80MB", "Backlog", "Medium", ["mobile", "performance"]),
    ("Story", "Per-post mute option", "Backlog", "Low", ["mobile"]),
    ("Bug", "Like count off by one after rapid taps", "Backlog", "Low", ["mobile"]),
    ("Story", "Animated reactions", "Backlog", "Low", ["mobile"]),
    ("Bug", "Status bar color wrong inside profile sheet", "Backlog", "Low", ["ios"]),
    ("Task", "Add Crashlytics for ANR detection", "Backlog", "Medium", ["android"]),
    ("Bug", "Background fetch never fires on iOS 17.2", "Backlog", "High", ["ios", "regression"]),
    ("Story", "Recently viewed list on profile", "Backlog", "Low", ["mobile"]),
    ("Bug", "Long-press menu missing 'Copy link' option", "Backlog", "Low", ["mobile"]),
    ("Task", "Remove Crashlytics legacy SDK", "Backlog", "Low", ["mobile", "tech-debt"]),
    ("Story", "Two-factor auth via authenticator app", "Backlog", "Medium", ["mobile", "security"]),
    ("Bug", "Username uniqueness check is case-sensitive", "Backlog", "Medium", ["backend", "mobile"]),
    ("Story", "Picture-in-picture for video player", "Backlog", "Medium", ["ios"]),
    ("Bug", "App icon badge does not clear after open", "Backlog", "Low", ["mobile"]),
    ("Task", "Update Firebase SDKs across both platforms", "Backlog", "Low", ["mobile", "tech-debt"]),
]
