"""SUP (Customer Support) issues - ~50 issues, support-kanban workflow."""

from __future__ import annotations


ISSUES = [
    # ---- A few hand-curated open tickets ----
    {
        "id_hint": 1,
        "type": "Bug",
        "summary": "Customer cannot upload profile photo from Pixel 8",
        "status": "Working",
        "priority": "High",
        "owner": "user_dani_haddad",
        "labels": ["customer-reported", "android"],
        "description": (
            "Customer reports the upload button does nothing on Pixel 8 running Android 14.\n\n"
            "Customer impact: cannot complete onboarding.\n"
            "Workaround given: complete onboarding on web."
        ),
        "created_offset_days": -3,
        "updated_offset_days": 0,
        "custom_fields": {
            "cf_root_cause": "Code defect",
            "cf_customer_impact": "Blocks onboarding completion (~12 tickets this week).",
        },
    },
    {
        "id_hint": 2,
        "type": "Bug",
        "summary": "Spam filter flagging legitimate emails from <customer>.io",
        "status": "Triaged",
        "priority": "Medium",
        "owner": "user_devon_lee",
        "labels": ["customer-reported", "backend", "blocked"],
        "created_offset_days": -5,
        "updated_offset_days": -1,
        "custom_fields": {"cf_root_cause": "Third-party"},
    },
    {
        "id_hint": 3,
        "type": "Task",
        "summary": "Refund request for duplicate charge",
        "status": "Resolved",
        "priority": "High",
        "owner": "user_yuki_tanaka",
        "labels": ["customer-reported"],
        "created_offset_days": -2,
        "updated_offset_days": -1,
        "resolution": "Fixed",
    },
    {
        "id_hint": 4,
        "type": "Bug",
        "summary": "User cannot log in - says 'invalid credentials' on correct password",
        "status": "Working",
        "priority": "Highest",
        "owner": "user_dani_haddad",
        "labels": ["customer-reported", "urgent"],
        "description": (
            "Affected user has correct credentials (verified via password reset). After reset they "
            "can log in once but next session fails again. Smells like a session-store bug."
        ),
        "created_offset_days": -1,
        "updated_offset_days": 0,
        "watchers": ["user_admin", "user_raj_patel"],
        "custom_fields": {"cf_root_cause": "Unknown", "cf_customer_impact": "Single user, but VIP account."},
    },
    {
        "id_hint": 5,
        "type": "Bug",
        "summary": "Notifications turned off after iOS upgrade",
        "status": "Working",
        "priority": "Medium",
        "owner": "user_yuki_tanaka",
        "labels": ["customer-reported", "ios"],
        "created_offset_days": -4,
        "updated_offset_days": -1,
    },
    {
        "id_hint": 6,
        "type": "Bug",
        "summary": "Search returns 0 results for queries with é/ä/ö",
        "status": "Triaged",
        "priority": "High",
        "owner": "user_devon_lee",
        "labels": ["customer-reported", "regression"],
        "description": "Linked to the platform-side search service issue. Working with PLAT.",
        "created_offset_days": -2,
        "updated_offset_days": 0,
        "links": [{"type": "duplicates", "target_hint": ("SCRUM", 10)}],
    },

    # ---- Resolved/closed tickets ----
    {
        "id_hint": 7,
        "type": "Bug",
        "summary": "Payment page 500s on Safari 16",
        "status": "Closed",
        "priority": "High",
        "owner": "user_yuki_tanaka",
        "labels": ["customer-reported"],
        "created_offset_days": -15,
        "updated_offset_days": -8,
        "resolution": "Fixed",
    },
    {
        "id_hint": 8,
        "type": "Bug",
        "summary": "Receipts show $0 for upgraded plan",
        "status": "Closed",
        "priority": "Medium",
        "owner": "user_dani_haddad",
        "labels": ["customer-reported"],
        "created_offset_days": -20,
        "updated_offset_days": -14,
        "resolution": "Fixed",
    },
    {
        "id_hint": 9,
        "type": "Task",
        "summary": "Bulk-import help: customer has 5k users to seed",
        "status": "Closed",
        "priority": "Medium",
        "owner": "user_devon_lee",
        "labels": ["customer-reported"],
        "created_offset_days": -25,
        "updated_offset_days": -22,
        "resolution": "Fixed",
    },
    {
        "id_hint": 10,
        "type": "Bug",
        "summary": "Mention notifications not arriving for some users",
        "status": "Closed",
        "priority": "Medium",
        "owner": "user_yuki_tanaka",
        "labels": ["customer-reported"],
        "created_offset_days": -30,
        "updated_offset_days": -25,
        "resolution": "Fixed",
    },
]

# Filler tickets across the support kanban. Status is varied.
FILLER = [
    ("Bug", "User reports app crash on opening attachments > 10MB", "Open", "Medium", ["customer-reported", "mobile"]),
    ("Bug", "Confused about how to share a post privately", "Triaged", "Low", ["customer-reported"]),
    ("Bug", "Two-factor SMS not arriving for +44 numbers", "Working", "High", ["customer-reported", "regression"]),
    ("Task", "Customer wants a CSV export of comments", "Open", "Low", ["customer-reported"]),
    ("Bug", "Profile name change does not persist after sign-out", "Working", "Medium", ["customer-reported"]),
    ("Bug", "Invite link expires immediately", "Triaged", "High", ["customer-reported", "regression"]),
    ("Bug", "GDPR data export missing comments older than 1y", "Working", "Medium", ["customer-reported", "security"]),
    ("Task", "Increase upload limit for verified accounts", "Open", "Medium", ["customer-reported"]),
    ("Bug", "Plus-sign in email rejected on signup", "Resolved", "Low", ["customer-reported"]),
    ("Bug", "App crashes on opening from notification on Android 10", "Working", "Medium", ["customer-reported", "android"]),
    ("Task", "How do I cancel my subscription?", "Closed", "Low", ["customer-reported"]),
    ("Bug", "Subscription auto-renews despite cancel", "Resolved", "High", ["customer-reported"]),
    ("Bug", "Profile image stretched on iPad", "Resolved", "Low", ["customer-reported", "ios"]),
    ("Bug", "Welcome email not arriving for new signups", "Triaged", "High", ["customer-reported", "regression"]),
    ("Task", "Account merge for a customer with two accounts", "Working", "Medium", ["customer-reported"]),
    ("Bug", "DMs lost after re-installing app", "Open", "High", ["customer-reported", "regression"]),
    ("Bug", "Push notifications stop after a week of use", "Triaged", "Medium", ["customer-reported"]),
    ("Bug", "Notifications go to wrong device when signed in on multiple", "Working", "Medium", ["customer-reported"]),
    ("Task", "Request: dark theme on web", "Closed", "Low", ["customer-reported"]),
    ("Bug", "Web checkout: card form jitters on Firefox", "Open", "Low", ["customer-reported"]),
    ("Bug", "Account deletion stuck in 'pending'", "Working", "High", ["customer-reported", "urgent"]),
    ("Task", "Customer wants invoice for past 6 months", "Closed", "Low", ["customer-reported"]),
    ("Bug", "Image rotation incorrect after upload on Android", "Closed", "Low", ["customer-reported", "android"]),
    ("Task", "Help porting their old data export", "Closed", "Medium", ["customer-reported"]),
    ("Bug", "Notification preference UI doesn't save selection", "Working", "Medium", ["customer-reported", "regression"]),
    ("Bug", "Web app won't accept passwords longer than 64 chars", "Closed", "Low", ["customer-reported"]),
    ("Task", "How to bulk-archive old posts", "Closed", "Low", ["customer-reported"]),
    ("Bug", "Search bar shifts position on iPad in landscape", "Closed", "Low", ["customer-reported", "ios"]),
    ("Bug", "Mention autocomplete picks wrong user", "Resolved", "Medium", ["customer-reported"]),
    ("Bug", "Comments missing from email digest", "Resolved", "Medium", ["customer-reported"]),
    ("Task", "Customer wants SSO integration", "Triaged", "Medium", ["customer-reported"]),
    ("Bug", "Apple Sign In returns empty email", "Resolved", "Medium", ["customer-reported", "ios"]),
    ("Bug", "Notification badge stuck on app icon", "Closed", "Low", ["customer-reported"]),
    ("Bug", "Username displayed as raw markdown in some notifications", "Closed", "Low", ["customer-reported"]),
    ("Bug", "PDF export missing images", "Resolved", "Medium", ["customer-reported"]),
    ("Task", "Migrate single workspace to enterprise plan", "Closed", "Medium", ["customer-reported"]),
    ("Bug", "Date picker shows previous month after select", "Closed", "Low", ["customer-reported"]),
    ("Bug", "Profile QR code stretched in dark mode", "Closed", "Lowest", ["customer-reported"]),
    ("Task", "Help with API integration - rate limits", "Triaged", "Medium", ["customer-reported", "api"]),
    ("Bug", "App locale doesn't match device locale", "Open", "Low", ["customer-reported"]),
]
